---
name: sphinx build
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.cff'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install .
          pip install -r docs/requirements.txt
          
      - name: Build documentation
        run: |
          sphinx-build ./docs/source ./docs/_build/html/
           
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html/
          force_orphan: true
