---
name: sphinx build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.cff'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install .[doc]

      - name: Build documentation
        run: |
          sphinx-build ./docs/source ./docs/_build/html/

      - name: Setup gh-pages branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Check if gh-pages branch exists remotely
          if git ls-remote --heads origin gh-pages | grep gh-pages; then
            echo "gh-pages branch exists, cloning it"
            git clone https://github.com/${{ github.repository }}.git --branch gh-pages --single-branch gh-pages
          else
            echo "gh-pages branch doesn't exist, creating it"
            mkdir gh-pages
            cd gh-pages
            git init
            git remote add origin https://github.com/${{ github.repository }}.git
            git checkout -b gh-pages
            cd ..
          fi

      - name: Deploy to gh-pages
        run: |
          # Clear existing content but keep .git
          cd gh-pages
          find . -maxdepth 1 ! -name '.git' ! -name '.' ! -name '..' -exec rm -rf {} +
          
          # Copy new documentation
          cp -r ../docs/_build/html/* .
          touch .nojekyll
          
          # Commit and push
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update documentation" || exit 0
          git push origin gh-pages
...
